# Reference documentation
# https://docs.gitlab.com/ee/ci/yaml/README.html


image: python:3.6

before_script:
  - set -euo pipefail

stages:
  - lint
  - deploy

lint:
  image: python:3.6
  stage: lint
  script:
  - pip install -r requirements.txt
  - pylint app
  - pylint todo

deploy:
  image: ruby:2.4
  stage: deploy
  script:
  - gem install dpl
  - dpl --provider=heroku --app=todo-api-rd7qf9 --api-key=$HEROKU_API_KEY
  only:
  - master
