# Reference documentation
# https://docs.gitlab.com/ee/ci/yaml/README.html


image: python:3.6

before_script:
  - set -euo pipefail
  - pip install -r requirements.txt

stages:
  - lint
  - deploy

lint:
  stage: lint
  script:
  - pylint app
  - pylint todo


deploy:
  stage: deploy
  script:
  - apt-get update -qy
  - apt-get install -y ruby-full
  - gem install dpl
  - dpl --provider=heroku --app=todo-api-rd7qf9 --api-key=$HEROKU_API_KEY
  only:
  - master
