# Reference documentation
# https://docs.gitlab.com/ee/ci/yaml/README.html


image: python:3.6

before_script:
  - set -euo pipefail

stages:
  - lint
  - migrate
  - deploy

lint:
  image: python:3.6
  stage: lint
  script:
  - pip install -r requirements.txt
  - pip install .
  - pip install pylint
  - pylint app
  - pylint todo

migrate:
  image: python:3.6
  stage: migrate
  script:
  - pip install -r requirements.txt
  - pip install .
  - pip install alembic
  - alembic upgrade head
  only:
  - master

deploy:
  image: ruby:2.4
  stage: deploy
  script:
  - gem install dpl
  - dpl --provider=heroku --app=todo-api-rd7qf9 --api-key=$HEROKU_API_KEY
  only:
  - master
