# Reference documentation
# https://docs.gitlab.com/ee/ci/yaml/README.html


image: python:3.6

before_script:
  - set -euo pipefail
  - pip install -r requirements.txt

stages:
  - lint

lint:
  stage: lint
  script:
    - pylint app && pylint todo-api
  - pylint app
  - true && false
  - pylint todo
