"""add user_id column to boards table

Revision ID: 324e4958ce0e
Revises: 50c8e7d1f28f
Create Date: 2017-11-02 19:24:48.105137

"""
# pylint: skip-file

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '324e4958ce0e'
down_revision = '50c8e7d1f28f'
branch_labels = None
depends_on = None

default_user_id = 'auth0|59fa7f8f36ab8913ea5c32a6'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('user_id', sa.String(),
                                      nullable=False, server_default=default_user_id))
    op.alter_column('boards', 'user_id', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boards', 'user_id')
    # ### end Alembic commands ###
