"""add number column to tasks table

Revision ID: 50c8e7d1f28f
Revises: c1b883dbfff4
Create Date: 2017-10-31 18:18:23.022375

"""
# pylint: skip-file

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '50c8e7d1f28f'
down_revision = 'c1b883dbfff4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks',
                  sa.Column(
                      'number',
                      sa.Integer(),
                      nullable=False,
                      server_default="0"))
    op.alter_column('tasks', 'number', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'number')
    # ### end Alembic commands ###
